// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetApiNet.Data;

#nullable disable

namespace ProjetApiNet.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260610021601_AjoutColonnesChargement")]
    partial class AjoutColonnesChargement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("ProjetApiNet.Models.Camion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChauffeurId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupeTransportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Immatriculation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Kilometrage")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Modele")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChauffeurId");

                    b.HasIndex("GroupeTransportId");

                    b.HasIndex("Immatriculation")
                        .IsUnique();

                    b.ToTable("Camions");
                });

            modelBuilder.Entity("ProjetApiNet.Models.Chargement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CamionId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CarburantTotalLitres")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateHeureDepart")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateHeureRetour")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstCloture")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrimeChauffeurGNF")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrimeSupervGenGNF")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrimeSuperviseurGroupeGNF")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrimeSuperviseurZoneGNF")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Statut")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TarifGNF")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("ZoneMiniereId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CamionId");

                    b.HasIndex("ZoneMiniereId");

                    b.ToTable("Chargements");
                });

            modelBuilder.Entity("ProjetApiNet.Models.GroupeTransport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("SuperviseurGroupeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ZoneMiniereId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.HasIndex("SuperviseurGroupeId");

                    b.HasIndex("ZoneMiniereId");

                    b.ToTable("GroupesTransport");
                });

            modelBuilder.Entity("ProjetApiNet.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Identifiant")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SalaireMensuelGNF")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Identifiant")
                        .IsUnique();

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("ProjetApiNet.Models.ZoneMiniere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChargementsMaxParMois")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DistanceAllerRetour")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DistanceDepotZone")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tarification")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ToursMaxParJour")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("ZoneMinieres");
                });

            modelBuilder.Entity("ProjetApiNet.Models.Camion", b =>
                {
                    b.HasOne("ProjetApiNet.Models.Utilisateur", "Chauffeur")
                        .WithMany("CamionsConduits")
                        .HasForeignKey("ChauffeurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjetApiNet.Models.GroupeTransport", "GroupeTransport")
                        .WithMany("Camions")
                        .HasForeignKey("GroupeTransportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chauffeur");

                    b.Navigation("GroupeTransport");
                });

            modelBuilder.Entity("ProjetApiNet.Models.Chargement", b =>
                {
                    b.HasOne("ProjetApiNet.Models.Camion", "Camion")
                        .WithMany("Chargements")
                        .HasForeignKey("CamionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetApiNet.Models.ZoneMiniere", "ZoneMiniere")
                        .WithMany("Chargements")
                        .HasForeignKey("ZoneMiniereId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Camion");

                    b.Navigation("ZoneMiniere");
                });

            modelBuilder.Entity("ProjetApiNet.Models.GroupeTransport", b =>
                {
                    b.HasOne("ProjetApiNet.Models.Utilisateur", "SuperviseurGroupe")
                        .WithMany("GroupesSupervises")
                        .HasForeignKey("SuperviseurGroupeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjetApiNet.Models.ZoneMiniere", "ZoneMiniere")
                        .WithMany("GroupesTransport")
                        .HasForeignKey("ZoneMiniereId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SuperviseurGroupe");

                    b.Navigation("ZoneMiniere");
                });

            modelBuilder.Entity("ProjetApiNet.Models.Camion", b =>
                {
                    b.Navigation("Chargements");
                });

            modelBuilder.Entity("ProjetApiNet.Models.GroupeTransport", b =>
                {
                    b.Navigation("Camions");
                });

            modelBuilder.Entity("ProjetApiNet.Models.Utilisateur", b =>
                {
                    b.Navigation("CamionsConduits");

                    b.Navigation("GroupesSupervises");
                });

            modelBuilder.Entity("ProjetApiNet.Models.ZoneMiniere", b =>
                {
                    b.Navigation("Chargements");

                    b.Navigation("GroupesTransport");
                });
#pragma warning restore 612, 618
        }
    }
}
