// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetApiNet.Data;

#nullable disable

namespace ProjetApiNet.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ProjetApiNet.Models.Camion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChauffeurId")
                        .HasColumnType("int");

                    b.Property<int>("GroupeTransportId")
                        .HasColumnType("int");

                    b.Property<string>("Immatriculation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("Kilometrage")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Modele")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ChauffeurId");

                    b.HasIndex("GroupeTransportId");

                    b.HasIndex("Immatriculation")
                        .IsUnique();

                    b.ToTable("Camions");
                });

            modelBuilder.Entity("ProjetApiNet.Models.Chargement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CamionId")
                        .HasColumnType("int");

                    b.Property<decimal>("CarburantTotalLitres")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("DateHeureDepart")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateHeureRetour")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("EstCloture")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("PrimeChauffeurGNF")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrimeSupervGenGNF")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrimeSuperviseurGroupeGNF")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrimeSuperviseurZoneGNF")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<decimal>("TarifGNF")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ZoneMiniereId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CamionId");

                    b.HasIndex("ZoneMiniereId");

                    b.ToTable("Chargements");
                });

            modelBuilder.Entity("ProjetApiNet.Models.GroupeTransport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("SuperviseurGroupeId")
                        .HasColumnType("int");

                    b.Property<int>("ZoneMiniereId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.HasIndex("SuperviseurGroupeId");

                    b.HasIndex("ZoneMiniereId");

                    b.ToTable("GroupesTransport");
                });

            modelBuilder.Entity("ProjetApiNet.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Identifiant")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<decimal>("SalaireMensuelGNF")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Identifiant")
                        .IsUnique();

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("ProjetApiNet.Models.ZoneMiniere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChargementsMaxParMois")
                        .HasColumnType("int");

                    b.Property<decimal>("DistanceAllerRetour")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DistanceDepotZone")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("Tarification")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ToursMaxParJour")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("ZoneMinieres");
                });

            modelBuilder.Entity("ProjetApiNet.Models.Camion", b =>
                {
                    b.HasOne("ProjetApiNet.Models.Utilisateur", "Chauffeur")
                        .WithMany("CamionsConduits")
                        .HasForeignKey("ChauffeurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjetApiNet.Models.GroupeTransport", "GroupeTransport")
                        .WithMany("Camions")
                        .HasForeignKey("GroupeTransportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chauffeur");

                    b.Navigation("GroupeTransport");
                });

            modelBuilder.Entity("ProjetApiNet.Models.Chargement", b =>
                {
                    b.HasOne("ProjetApiNet.Models.Camion", "Camion")
                        .WithMany("Chargements")
                        .HasForeignKey("CamionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetApiNet.Models.ZoneMiniere", "ZoneMiniere")
                        .WithMany("Chargements")
                        .HasForeignKey("ZoneMiniereId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Camion");

                    b.Navigation("ZoneMiniere");
                });

            modelBuilder.Entity("ProjetApiNet.Models.GroupeTransport", b =>
                {
                    b.HasOne("ProjetApiNet.Models.Utilisateur", "SuperviseurGroupe")
                        .WithMany("GroupesSupervises")
                        .HasForeignKey("SuperviseurGroupeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjetApiNet.Models.ZoneMiniere", "ZoneMiniere")
                        .WithMany("GroupesTransport")
                        .HasForeignKey("ZoneMiniereId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SuperviseurGroupe");

                    b.Navigation("ZoneMiniere");
                });

            modelBuilder.Entity("ProjetApiNet.Models.Camion", b =>
                {
                    b.Navigation("Chargements");
                });

            modelBuilder.Entity("ProjetApiNet.Models.GroupeTransport", b =>
                {
                    b.Navigation("Camions");
                });

            modelBuilder.Entity("ProjetApiNet.Models.Utilisateur", b =>
                {
                    b.Navigation("CamionsConduits");

                    b.Navigation("GroupesSupervises");
                });

            modelBuilder.Entity("ProjetApiNet.Models.ZoneMiniere", b =>
                {
                    b.Navigation("Chargements");

                    b.Navigation("GroupesTransport");
                });
#pragma warning restore 612, 618
        }
    }
}
